# Generated by Django 3.0.6 on 2020-05-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=2048, verbose_name='URL')),
                ('request_code', models.CharField(max_length=50, verbose_name='request_code')),
                ('arg1', models.CharField(max_length=255, verbose_name='arg1')),
                ('arg2', models.IntegerField(blank=True, default=0, verbose_name='arg2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
        ),
    ]
